DefaultContentLanguage = "en"
baseURL = "https://ruskbakery.netlify.com/"
defaultContentLanguageInSubdir = true
enableGitInfo = false
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
pygmentsCodeFences = false
summaryLength = 10
theme = "navigator-hugo"
title = "Rusk Bakery"
[Languages.en]
dateFormat = "January 2, 2006"
footerAboutTitle = "About"
footerDescription = "Shahjahanpur(u.p), Indian based organization, Popular Parag food product from many years has been the source of ending cravings for tasty Rusk."
footerQuicklinkTitle = ""
footerServiceTitle = ""
footerSubscribeTitle = "Subscribe"
home = "Home"
about="About"
gifting="Gifting"
service="Service"
languageCode = "en-us"
logo = "/images/logo.png"
menufixed = false
title = "Rusk Bakery"
weight = 2
[Languages.en.params.aboutSm]
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"
enable = false
title = "We have explored the digital landscape with passion for a long time"
[Languages.en.params.blog]
enable = false
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "Blog."
topTitle = "OUR UNTOLD STORY"
[Languages.en.params.contact]
address = "Popular Parag Food Product,NH 24 highway <br> Bareilly Mord ,Shahjahanpur"
dribbble = ""
enable = true
facebook = "https://www.facebook.com/"
instagram = "https://www.instagram.com/"
linkedin = "https://www.linkedin.com/"
mapLatitude = ""
mapLongitude = ""
mapMarker = ""
phone = "+91 9336191255"
subtitle = ""
title = "Contact Us."
topTitle = "DROP US A NOTE"
[Languages.en.params.cta]
bg = "images/call-to-action/call-to-action-bg-2.jpg"
btnText = "Contact Us"
enable = false
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
title = "Let's Create Something Together"
[Languages.en.params.hero]
btnText = ""
btnURL = ""
button = false
description = "JAI G is one of the upcoming confectionery brands of India. Shahjahanpur(u.p), Indian based organization, Popular Parag food product from many years has been the source of ending cravings for tasty Rusk.\nThe company which started is an inspiration to the many firms and favorite of numerous foodies for getting the items of their desired taste. In our semi-automatic production set up, all the offered varieties are prepared in a systematic way, keeping up the high standards of hygiene & taste. Further, our customer-oriented approaches that are designed to please the clients and give them ease in working with us are also bringing to us the desired growth and success."
enable = true
heading = "JAI G"
videoThumb = "uploads/home.jpg"
[Languages.hin]
dateFormat = "January 2, 2006"
footerAboutTitle = "About"
footerDescription = "Shahjahanpur(u.p), Indian based organization, Popular Parag food product from many years has been the source of ending cravings for tasty Rusk."
footerQuicklinkTitle = ""
footerServiceTitle = ""
footerSubscribeTitle = "Subscribe"
home = "Home"
about="About"
gifting="Gifting"
service="Service"
languageCode = "en-us"
logo = "/images/logo.png"
menufixed = false
title = "Rusk Bakery"
weight = 2
[Languages.hin.params.aboutSm]
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quae deleniti ipsa labore necessitatibus culpa veritatis quo accusantium, neque enim ea ad eaque iure, quas tempore velit, quibusdam dolor illo! Explicabo. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid quisquam maiores iste soluta, nihil dolorem?"
enable = false
title = "We have explored the digital landscape with passion for a long time"
[Languages.hin.params.blog]
enable = false
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "Blog."
topTitle = "OUR UNTOLD STORY"
[Languages.hin.params.contact]
address = "Popular Parag Food Product,NH 24 highway <br> Bareilly Mord ,Shahjahanpur"
dribbble = ""
enable = true
facebook = "https://www.facebook.com/"
instagram = "https://www.instagram.com/"
linkedin = "https://www.linkedin.com/"
mapLatitude = ""
mapLongitude = ""
mapMarker = ""
phone = "+91 9336191255"
subtitle = ""
title = "Contact Us."
topTitle = "DROP US A NOTE"
[Languages.hin.params.cta]
bg = "images/call-to-action/call-to-action-bg-2.jpg"
btnText = "Contact Us"
enable = false
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
title = "Let's Create Something Together"
[Languages.hin.params.hero]
btnText = ""
btnURL = ""
button = false
description = "JAI G is one of the upcoming confectionery brands of India. Shahjahanpur(u.p), Indian based organization, Popular Parag food product from many years has been the source of ending cravings for tasty Rusk.\nThe company which started is an inspiration to the many firms and favorite of numerous foodies for getting the items of their desired taste. In our semi-automatic production set up, all the offered varieties are prepared in a systematic way, keeping up the high standards of hygiene & taste. Further, our customer-oriented approaches that are designed to please the clients and give them ease in working with us are also bringing to us the desired growth and success."
enable = true
heading = "JAI G"
videoThumb = "uploads/home.jpg"
[[Params.listeLangues]]
code = "hin"
[[Params.listeLangues]]
author = "Koders"
code = "en"
description = "This is meta description"
[menu]
quicklink = []
service = []

